-- MySQL Script generated by MySQL Workbench
-- 06/01/15 23:02:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `funcionarios_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionarios_tipos` ;

CREATE TABLE IF NOT EXISTS `funcionarios_tipos` (
  `id_funcionario_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `esatdo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id_funcionario_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionarios` ;

CREATE TABLE IF NOT EXISTS `funcionarios` (
  `run_funcionario` VARCHAR(9) NOT NULL,
  `id_funcionario_tipo` INT NOT NULL,
  `nombre1` VARCHAR(45) NOT NULL,
  `nombre2` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`run_funcionario`),
  INDEX `fk_funcionarios_funcionarios_tipos1_idx` (`id_funcionario_tipo` ASC),
  CONSTRAINT `fk_funcionarios_funcionarios_tipos1`
    FOREIGN KEY (`id_funcionario_tipo`)
    REFERENCES `funcionarios_tipos` (`id_funcionario_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documentos_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documentos_tipos` ;

CREATE TABLE IF NOT EXISTS `documentos_tipos` (
  `id_documento_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `estado` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id_documento_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documentos` ;

CREATE TABLE IF NOT EXISTS `documentos` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `id_documento_tipo` INT NOT NULL,
  `run_funcionario_creador` VARCHAR(9) NOT NULL,
  `fecha_hora_creacion` DATETIME NOT NULL,
  `fecha_hora_ultima_vista` DATETIME NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `ruta` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_documentos_tipos_documentos_idx` (`id_documento_tipo` ASC),
  INDEX `fk_documentos_funcionarios1_idx` (`run_funcionario_creador` ASC),
  CONSTRAINT `fk_documentos_tipos_documentos`
    FOREIGN KEY (`id_documento_tipo`)
    REFERENCES `documentos_tipos` (`id_documento_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_funcionarios1`
    FOREIGN KEY (`run_funcionario_creador`)
    REFERENCES `funcionarios` (`run_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busquedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `busquedas` ;

CREATE TABLE IF NOT EXISTS `busquedas` (
  `id_busqueda` INT NOT NULL AUTO_INCREMENT,
  `run_funcionario` VARCHAR(9) NOT NULL,
  `id_documento` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT 1,
  INDEX `fk_funcionarios_has_documentos_documentos1_idx` (`id_documento` ASC),
  INDEX `fk_funcionarios_has_documentos_funcionarios1_idx` (`run_funcionario` ASC),
  PRIMARY KEY (`id_busqueda`),
  CONSTRAINT `fk_funcionarios_has_documentos_funcionarios1`
    FOREIGN KEY (`run_funcionario`)
    REFERENCES `funcionarios` (`run_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_has_documentos_documentos1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `documentos` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

